name: Publish to GitHub Packages

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Configure pip for GitHub Packages
      run: |
        echo "[global]" >> ~/.pip/pip.conf
        echo "extra-index-url = https://pypi.pkg.github.com/ahmetxhero/simple/" >> ~/.pip/pip.conf
    
    - name: Publish to GitHub Packages
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
      run: twine upload dist/*
    
    - name: Create package release
      run: |
        echo "Package published to GitHub Packages!"
        echo "Install with: pip install --index-url https://pypi.pkg.github.com/ahmetxhero/simple/ scanhero"
